@server=http://localhost:4004
@path=/nomina/aprobaciones


### Metadata
GET {{server}}{{path}}/$metadata

### GET List Report — lista de tareas
GET {{server}}{{path}}/TareasInbox

###

### GET Object Page — detalle de tarea
GET {{server}}{{path}}/TareasInbox(instanceID='mock-task-001')

###

### GET Composición proveedores
GET {{server}}{{path}}/TareasInbox(instanceID='mock-task-001')/proveedores

###

### GET Composición adjuntos
GET {{server}}{{path}}/TareasInbox(instanceID='mock-task-001')/adjuntos

###

### GET Composición aprobadores
GET {{server}}{{path}}/TareasInbox(instanceID='mock-task-001')/aprobadores