@server=http://localhost:4004
@path=/nomina/aprobaciones

### GET Metadata
GET {{server}}{{path}}/$metadata
Authorization: Basic YWxpY2U6YWxpY2U=


### GET Constantes
GET {{server}}{{path}}/obtenerConstantes
Authorization: Basic YWxpY2U6YWxpY2U=